### ISSUE TITLE
Auto Populate Naming Series and Update stock automatically

### ISSUE THREAD

**Issue by revant** [mntechnique/skynpronaturals_erpnext#1]
Spec steps
1. Property Setter - Set Update stock as default
2. Add custom field on Sales Invoice - spn_warehouse - Link - Warehouse
3. Delivery Warehouse is selected in above field
4. As per delivery warehouse auto populate items child table warehouse

Naming Series Logic for Sales Invoice and Sales Return Invoice add (RET)

Source : Warehouse from the custom field added.
Destination : Customer's Terrirory

| Source | Destination | Registered | Naming Series |
| --- | --- | --- | --- |
| Assam | Assam | Registered | GV-.##### |
| Assam | Assam | Unregistered | GU-.##### |
| Maharashtra | Maharashtra | Registered | BV-.##### |
| Maharashtra | Maharashtra | Unregistered | BU-.##### |
| Assam | India | Registered | GC-.##### |
| Assam | India | Unregistered | GC-.##### |
| Maharashtra | India | Registered | BC-.##### |
| Maharashtra | India | Unregistered | BC-.##### |

**ETA :** 4hrs

**Workaround:** 
In ERPNext, Sales Invoice Report can track Invoices by many fields, e.g. Territory, Customer, Items, etc. Explore Report Builder Feature.

![salesinvoicereportbuilder](https://cloud.githubusercontent.com/assets/1040161/19594817/806bf040-97a4-11e6-9159-901322415a98.png)

@gaurav-naik

**Comment by gaurav-naik** [comment]
Add VAT No as Custom Field on Customer doctype.

In Sales Invoice, "Registered" implies that the Customer has non-null VAT No.

**Comment by niharRaut** [comment]
**As per the Mail from Mr. Sudhakar on Fri, Oct 21, 2016 at 5:04 PM**
The naming series is a requirement and must be done as specified. Please complete the same asap and inform.  

Also, we spoke of the sales returns invoice nos.   Note this will not be a separate series but a continuous series. eg. If a invoice BC1101 is created on 21/10/16 and we need to take sales returns/partial returns of it on 10/11/16.  And the invoice no. in this series is BC1155 on 10/11/16, then the sales return taken on that day will have invoice no. BC1156.  and this will have reference of the original invoice on it.
